# Generated by Django 5.0.3 on 2024-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacbookInventry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventry_id', models.IntegerField()),
                ('deviceuser_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('photo', models.CharField(max_length=200)),
                ('tracking_no', models.CharField(max_length=20)),
                ('other_info', models.TextField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=122)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=122)),
            ],
        ),
    ]
