# Generated by Django 5.0.3 on 2024-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventry',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
