# Generated by Django 5.0.3 on 2024-04-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_macbookinventry_delete_macbookinventry2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MacbookInuventry',
        ),
    ]
