# Generated by Django 5.0.3 on 2024-04-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_macbookinventry_usb_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macbookinventry',
            name='usb_idd',
        ),
    ]
