# Generated by Django 5.0.3 on 2024-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_macbookinventry_usb_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='macbookinventry',
            name='usb_idf',
            field=models.IntegerField(null=True),
        ),
    ]
