# Generated by Django 5.0.3 on 2024-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_inventrytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='inventry',
            name='photo',
            field=models.ManyToManyField(to='src.photo'),
        ),
    ]
