# Generated by Django 5.0.3 on 2024-04-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_macbookinventry_usb_idf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macbookinventry',
            name='usb_idf',
        ),
    ]
